### PR TITLE
 update to typescript

### PR DESCRIPTION
**Pull request by bluelovers**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rmainseas** [comment]
Looks like this has merge conflicts. Also, if this is merged then it will break for people not using typescript (since there is no compiled js version provided). I'd suggest that the CI system needs to be updated to auto-ship a compiled JS version to npm...

**Comment by joshmarinacci** [comment]
Can you fix the conflicts and add an build command to generate the final JS from the typescript?

**Comment by bluelovers** [comment]
i think u should ignore conflicts , because it is from javascript to typescript

the generate js , u can use `tsc` command for build it

**Comment by robertmain** [comment]
@bluelovers you literally can't do that because the conflict markers (`<<<`) in the code will break interpretation. Ideally, one would commit typescript to GitHub and then ship javascript to npm.

**Comment by bluelovers** [comment]
can manual merge in local

**Comment by rmainseas** [comment]
That's not merging the pull request, that's merging the branch. And you
still need to remove the conflict makers. It's also a really bad idea in
this situation. GitHub tries to prevent this for a reason. Please don't
encourage people to do silly things.

Just fix your merge conflicts like an adult.

**Comment by robertmain** [comment]
That's not merging the pull request, that's merging the branch. And you need to remove the conflict makers. It's also a really bad idea in situation.

GitHub tries to prevent this for a reason. Please don't encourage people to do silly things like this. Instead, fix your merge conflicts like an adult.

Also, you didn't fill out the PR template explaining the changes in your PR.

**Comment by josh-hemphill** [comment]
I might take a crack at a typescript migration if the maintainers would still be interested in seeing one. I have several github typescript projects that create builds targeting both node CJS, node MJS, and Deno. Though that's one reason you'd want to commit the built files to version control, so that other platforms that just clone the repo to distribute files still have the built files (aka, Deno.land... 😬 )

**Comment by Codezigineer** [comment]
Why should we migrate to TypeScript if we won't have support for non-TS environs & we already have [types?](https://github.com/joshmarinacci/node-pureimage/tree/master/types) Since we already have types, we can already support TS projects that want to integrate.

**Pull request closed without merging**
